/*--------------------------------------------------------------------------*/
/**@file   my_adkey.h
   @brief  AD°´¼ü¶¨Òå
   @details
   @author
   @date   2010-12-13
   @note
*/
/*----------------------------------------------------------------------------*/
#include "Custom_config.h"

#ifndef	_MY_ADKEY_H_
#define _MY_ADKEY_H_

#if 1
#define MUSIC_ADKEY_SHORT_00		NO_MSG
#define MUSIC_ADKEY_SHORT_01		MSG_VOL_UP
#define MUSIC_ADKEY_SHORT_02		MSG_VOL_DOWN
#define MUSIC_ADKEY_SHORT_03		MSG_NEXT_PLAYMODE
#define MUSIC_ADKEY_SHORT_04		MSG_MUSIC_NEXT_EQ
#define MUSIC_ADKEY_SHORT_05		MSG_NEXT_WORKMODE
#define MUSIC_ADKEY_SHORT_06		MSG_MUSIC_PREV_FILE
#define MUSIC_ADKEY_SHORT_07		MSG_MUSIC_NEXT_FILE
#define MUSIC_ADKEY_SHORT_08		MSG_MUSIC_PP
#define MUSIC_ADKEY_SHORT_09		MSG_POWER

#define MUSIC_ADKEY_LONG_00		NO_MSG
#define MUSIC_ADKEY_LONG_01		NO_MSG
#define MUSIC_ADKEY_LONG_02		NO_MSG
#define MUSIC_ADKEY_LONG_03		NO_MSG
#define MUSIC_ADKEY_LONG_04		MSG_ALTERNATIVE_DEVICE
#define MUSIC_ADKEY_LONG_05		NO_MSG
#define MUSIC_ADKEY_LONG_06		NO_MSG
#define MUSIC_ADKEY_LONG_07		NO_MSG
#define MUSIC_ADKEY_LONG_08		NO_MSG
#define MUSIC_ADKEY_LONG_09		NO_MSG


#define MUSIC_ADKEY_HOLD_00		NO_MSG
#define MUSIC_ADKEY_HOLD_01		MSG_VOL_UP
#define MUSIC_ADKEY_HOLD_02		MSG_VOL_DOWN
#define MUSIC_ADKEY_HOLD_03		NO_MSG
#define MUSIC_ADKEY_HOLD_04		NO_MSG
#define MUSIC_ADKEY_HOLD_05		NO_MSG
#define MUSIC_ADKEY_HOLD_06		MSG_MUSIC_FR
#define MUSIC_ADKEY_HOLD_07		MSG_MUSIC_FF
#define MUSIC_ADKEY_HOLD_08		NO_MSG
#define MUSIC_ADKEY_HOLD_09		NO_MSG

#define MUSIC_ADKEY_L_UP_00		NO_MSG
#define MUSIC_ADKEY_L_UP_01		NO_MSG
#define MUSIC_ADKEY_L_UP_02		NO_MSG
#define MUSIC_ADKEY_L_UP_03		NO_MSG
#define MUSIC_ADKEY_L_UP_04		NO_MSG
#define MUSIC_ADKEY_L_UP_05		NO_MSG
#define MUSIC_ADKEY_L_UP_06		MSG_MUSIC_FFR_DONE
#define MUSIC_ADKEY_L_UP_07		MSG_MUSIC_FFR_DONE
#define MUSIC_ADKEY_L_UP_08		NO_MSG
#define MUSIC_ADKEY_L_UP_09		NO_MSG


//3 FM ADKEY
#define RADIO_ADKEY_SHORT_00		NO_MSG
#define RADIO_ADKEY_SHORT_01		MSG_VOL_UP
#define RADIO_ADKEY_SHORT_02		MSG_VOL_DOWN
#define RADIO_ADKEY_SHORT_03		MSG_RADIO_SCAN_ALL
#define RADIO_ADKEY_SHORT_04		MSG_MUSIC_NEXT_EQ
#define RADIO_ADKEY_SHORT_05		MSG_NEXT_WORKMODE
#define RADIO_ADKEY_SHORT_06		MSG_RADIO_PREV_STEP
#define RADIO_ADKEY_SHORT_07		MSG_RADIO_NEXT_STEP
#define RADIO_ADKEY_SHORT_08		MSG_CHANGE_RADIO_MODE
#define RADIO_ADKEY_SHORT_09		MSG_POWER

#define RADIO_ADKEY_LONG_00		NO_MSG
#define RADIO_ADKEY_LONG_01		NO_MSG
#define RADIO_ADKEY_LONG_02		NO_MSG
#define RADIO_ADKEY_LONG_03		NO_MSG
#define RADIO_ADKEY_LONG_04		NO_MSG
#define RADIO_ADKEY_LONG_05		NO_MSG
#define RADIO_ADKEY_LONG_06		MSG_RADIO_SCAN_ALL_DOWN
#define RADIO_ADKEY_LONG_07		MSG_RADIO_SCAN_ALL_UP
#define RADIO_ADKEY_LONG_08		NO_MSG
#define RADIO_ADKEY_LONG_09		NO_MSG	

#define RADIO_ADKEY_HOLD_00		NO_MSG
#define RADIO_ADKEY_HOLD_01		MSG_VOL_UP
#define RADIO_ADKEY_HOLD_02		MSG_VOL_DOWN
#define RADIO_ADKEY_HOLD_03		NO_MSG
#define RADIO_ADKEY_HOLD_04		NO_MSG
#define RADIO_ADKEY_HOLD_05		NO_MSG
#define RADIO_ADKEY_HOLD_06		NO_MSG
#define RADIO_ADKEY_HOLD_07		NO_MSG
#define RADIO_ADKEY_HOLD_08		NO_MSG
#define RADIO_ADKEY_HOLD_09		NO_MSG

#define RADIO_ADKEY_L_UP_00		NO_MSG
#define RADIO_ADKEY_L_UP_01		NO_MSG	
#define RADIO_ADKEY_L_UP_02		NO_MSG
#define RADIO_ADKEY_L_UP_03		NO_MSG
#define RADIO_ADKEY_L_UP_04		NO_MSG
#define RADIO_ADKEY_L_UP_05		NO_MSG
#define RADIO_ADKEY_L_UP_06		NO_MSG
#define RADIO_ADKEY_L_UP_07		NO_MSG
#define RADIO_ADKEY_L_UP_08		NO_MSG
#define RADIO_ADKEY_L_UP_09		NO_MSG

#endif


#ifdef USE_TWO_ADKEY

#define MUSIC_ADKEY2_SHORT_00		MSG_9
#define MUSIC_ADKEY2_SHORT_01		MSG_8
#define MUSIC_ADKEY2_SHORT_02		MSG_7
#define MUSIC_ADKEY2_SHORT_03		MSG_6
#define MUSIC_ADKEY2_SHORT_04		MSG_5
#define MUSIC_ADKEY2_SHORT_05		MSG_4
#define MUSIC_ADKEY2_SHORT_06		MSG_3
#define MUSIC_ADKEY2_SHORT_07		MSG_2
#define MUSIC_ADKEY2_SHORT_08		MSG_1
#define MUSIC_ADKEY2_SHORT_09		MSG_0

#define MUSIC_ADKEY2_LONG_00		NO_MSG
#define MUSIC_ADKEY2_LONG_01		NO_MSG
#define MUSIC_ADKEY2_LONG_02		NO_MSG
#define MUSIC_ADKEY2_LONG_03		NO_MSG
#define MUSIC_ADKEY2_LONG_04		NO_MSG
#define MUSIC_ADKEY2_LONG_05		NO_MSG
#define MUSIC_ADKEY2_LONG_06		NO_MSG
#define MUSIC_ADKEY2_LONG_07		NO_MSG
#define MUSIC_ADKEY2_LONG_08		NO_MSG
#define MUSIC_ADKEY2_LONG_09		NO_MSG


#define MUSIC_ADKEY2_HOLD_00		NO_MSG
#define MUSIC_ADKEY2_HOLD_01		NO_MSG
#define MUSIC_ADKEY2_HOLD_02		NO_MSG
#define MUSIC_ADKEY2_HOLD_03		NO_MSG
#define MUSIC_ADKEY2_HOLD_04		NO_MSG
#define MUSIC_ADKEY2_HOLD_05		NO_MSG
#define MUSIC_ADKEY2_HOLD_06		NO_MSG
#define MUSIC_ADKEY2_HOLD_07		NO_MSG
#define MUSIC_ADKEY2_HOLD_08		NO_MSG
#define MUSIC_ADKEY2_HOLD_09		NO_MSG

#define MUSIC_ADKEY2_L_UP_00		NO_MSG
#define MUSIC_ADKEY2_L_UP_01		NO_MSG
#define MUSIC_ADKEY2_L_UP_02		NO_MSG
#define MUSIC_ADKEY2_L_UP_03		NO_MSG
#define MUSIC_ADKEY2_L_UP_04		NO_MSG
#define MUSIC_ADKEY2_L_UP_05		NO_MSG
#define MUSIC_ADKEY2_L_UP_06		NO_MSG
#define MUSIC_ADKEY2_L_UP_07		NO_MSG
#define MUSIC_ADKEY2_L_UP_08		NO_MSG
#define MUSIC_ADKEY2_L_UP_09		NO_MSG

//3 FM ADKEY
#define RADIO_ADKEY2_SHORT_00		MSG_9
#define RADIO_ADKEY2_SHORT_01		MSG_8
#define RADIO_ADKEY2_SHORT_02		MSG_7
#define RADIO_ADKEY2_SHORT_03		MSG_6
#define RADIO_ADKEY2_SHORT_04		MSG_5
#define RADIO_ADKEY2_SHORT_05		MSG_4
#define RADIO_ADKEY2_SHORT_06		MSG_3
#define RADIO_ADKEY2_SHORT_07		MSG_2
#define RADIO_ADKEY2_SHORT_08		MSG_1
#define RADIO_ADKEY2_SHORT_09		MSG_0

#define RADIO_ADKEY2_LONG_00		NO_MSG
#define RADIO_ADKEY2_LONG_01		NO_MSG
#define RADIO_ADKEY2_LONG_02		NO_MSG
#define RADIO_ADKEY2_LONG_03		NO_MSG
#define RADIO_ADKEY2_LONG_04		NO_MSG
#define RADIO_ADKEY2_LONG_05		NO_MSG
#define RADIO_ADKEY2_LONG_06		NO_MSG	
#define RADIO_ADKEY2_LONG_07		NO_MSG
#define RADIO_ADKEY2_LONG_08		NO_MSG
#define RADIO_ADKEY2_LONG_09		NO_MSG	

#define RADIO_ADKEY2_HOLD_00		NO_MSG
#define RADIO_ADKEY2_HOLD_01		NO_MSG
#define RADIO_ADKEY2_HOLD_02		NO_MSG
#define RADIO_ADKEY2_HOLD_03		NO_MSG
#define RADIO_ADKEY2_HOLD_04		NO_MSG
#define RADIO_ADKEY2_HOLD_05		NO_MSG
#define RADIO_ADKEY2_HOLD_06		NO_MSG
#define RADIO_ADKEY2_HOLD_07		NO_MSG
#define RADIO_ADKEY2_HOLD_08		NO_MSG
#define RADIO_ADKEY2_HOLD_09		NO_MSG

#define RADIO_ADKEY2_L_UP_00		NO_MSG
#define RADIO_ADKEY2_L_UP_01		NO_MSG	
#define RADIO_ADKEY2_L_UP_02		NO_MSG
#define RADIO_ADKEY2_L_UP_03		NO_MSG
#define RADIO_ADKEY2_L_UP_04		NO_MSG
#define RADIO_ADKEY2_L_UP_05		NO_MSG
#define RADIO_ADKEY2_L_UP_06		NO_MSG
#define RADIO_ADKEY2_L_UP_07		NO_MSG
#define RADIO_ADKEY2_L_UP_08		NO_MSG
#define RADIO_ADKEY2_L_UP_09		NO_MSG

#endif

#endif

